/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.ui;

import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.TextArea;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import sistema.archivos.Archivo;

/**
 *
 * @author bruno
 */
public class VentanaCliente extends javax.swing.JFrame implements MouseListener{
    Color color1 = Color.BLACK;
    Color color2 = Color.RED;
    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
        initComponents();
        this.setLayout(new BorderLayout());
        definirParametrosIniciales();
        posicionarElementos();    
    }
    
    public void cargarTablero(String contenido, int filas, int columnas){
        try{
            JPanel tablero = new JPanel(new GridLayout(filas,columnas));
            String[] coordenadas = contenido.split("\n");
            for(int i = 0 ; i < coordenadas.length ; i++){
                String[] contenidoCoordenada = coordenadas[i].split(",");
                JPanel casilla = new JPanel();
                Label label = new Label("CASILLA X"+i);
                label.addMouseListener(this);
                casilla.add(label);
                casilla.setBackground(obtenerColorCasilla(contenidoCoordenada[0]));
                tablero.add(casilla);
            }
            add(tablero, BorderLayout.CENTER);
            pack();
        }catch(Exception  ex){
            ex.printStackTrace();
            System.out.println("error al cargar tablero");
        }
    }
    
    private Color obtenerColorCasilla(String parametro){
        switch(parametro){
            case "agua": return Color.BLUE;
            case "grama": return Color.GREEN;
            case "arbol": return Color.yellow;
            case "carretera": return Color.GRAY;
            case "montania": return Color.orange;
        }
        return Color.WHITE;
    }
    
    private void posicionarElementos(){
        //posicicionamiento elementos administrativos
        JPanel panelAdministrativo = new JPanel(new FlowLayout(FlowLayout.CENTER));
        panelAdministrativo.add(CboxCargaArchivos);
        panelAdministrativo.add(btnCargarArchivo);
        panelAdministrativo.add(btnCargarMapa);
        add(panelAdministrativo, BorderLayout.PAGE_START);
        //log no lo posicionamos con los elementos administrativos
        add(txtLog, BorderLayout.PAGE_END);
    }
    
    private void definirParametrosIniciales(){
        //definicion de caracteristicas
        setSize(1300, 900);
        
        //parametros 
        CboxCargaArchivos.addItem("Tropas Jugador 1");
        CboxCargaArchivos.addItem("Tropas Jugador 2");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".army", "army");
        fileChooser.setFileFilter(filtro);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        btnCargarArchivo = new javax.swing.JButton();
        CboxCargaArchivos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnCargarMapa = new javax.swing.JButton();

        btnCargarArchivo.setText("Cargar Tropas");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbtnCargarArchivo(evt);
            }
        });

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        btnCargarMapa.setText("Cargar Mapa");
        btnCargarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarMapaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbtnCargarArchivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbtnCargarArchivo
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == fileChooser.APPROVE_OPTION) {
            Archivo archivo = new Archivo();
            archivo.cargarTropas(fileChooser.getSelectedFile().getAbsolutePath(), (CboxCargaArchivos.getSelectedIndex() + 1));
        }
    }//GEN-LAST:event_btnbtnCargarArchivo

    private void btnCargarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarMapaActionPerformed
        main.Main.emisor.enviarPeticion("mapa");
    }//GEN-LAST:event_btnCargarMapaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxCargaArchivos;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnCargarMapa;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent me) {
        try{
            Label label = (Label)me.getSource();
            System.out.println("presionada: " + label.getText());   
        }catch(Exception ex){
            System.out.println("tocando otra cosa");
        }
    }

    @Override
    public void mousePressed(MouseEvent me) {
        
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        
    }

    @Override
    public void mouseExited(MouseEvent me) {
        
    }
}